### ISSUE TITLE
Host on Hugging Face Spaces

### ISSUE THREAD

**Issue by osanseviero** [lxe/simple-llama-finetuner#19]
Hey there!

Would there be interest in hosting this finetuner app on Hugging Face Spaces? (hf.co/spaces). This could be a duplicate-based Space that people duplicate and then train. An example that does this is https://huggingface.co/spaces/multimodalart/dreambooth-training . If there's interest, I'm happy to help and set up a Slack channel if you want to collaborate on it.

**Comment by lxe** [comment]
It costs money though to get a GPU space.

**Comment by osanseviero** [comment]
Hey there! Yes, assigning a GPU would cost. How we've usually approached is that a template is provided, people then duplicate and get/assign a GPU for their own usage, so you would not incur the price. We can also provide some grants if there's interest on that to support specific community projects

**Comment by lxe** [comment]
https://huggingface.co/spaces/lxe/simple-llama-finetuner

**Comment by lxe** [comment]
Done!
